Repository darshan-hpc/darshan, pull requests merged in 2022-10, with the labels that each got.

#823 TST: Python 3.11
  .github/workflows/main_ci.yml
Labels: testing, CI

#825 BUG: memleak part 4
  darshan-util/darshan-logutils.c
  darshan-util/pydarshan/darshan/backend/cffi_backend.py
Labels: bug, pydarshan

#827 BUG: Fix handling of forked processes in darshan-runtime
  darshan-runtime/lib/darshan-hdf5.c
  darshan-runtime/lib/darshan-lustre.c
  darshan-runtime/lib/darshan-mdhim.c
  darshan-runtime/lib/darshan-mpiio.c
  darshan-runtime/lib/darshan-pnetcdf.c
  darshan-runtime/lib/darshan-posix.c
  darshan-runtime/lib/darshan-stdio.c
  darshan-test/python_mpi_scripts/runtime_prog_issue_786.py
  darshan-test/python_runtime_tests.py
Labels: bug

#822 MAINT: mpl join() deprecation
  .github/workflows/main_ci.yml
  darshan-util/pydarshan/darshan/experimental/plots/data_access_by_filesystem.py
Labels: pydarshan, CI, maintenance

#835 CI: remove shared flag
  .github/workflows/main_ci.yml
  .github/workflows/runtime_ci.yml
Labels: CI, maintenance

#836 MAINT, TST: lxml optional skip
  .github/workflows/main_ci.yml
  darshan-util/pydarshan/darshan/tests/test_summary.py
  darshan-util/pydarshan/mypy.ini
Labels: pydarshan, CI, maintenance

#838 CI: test darshan-util
  .github/workflows/main_ci.yml
Labels: testing, CI
